# Generated by Django 5.2.4 on 2025-08-03 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='cause_of_problem',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='corrective_measure',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='equipment_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='shift',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='et_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='task_type',
            field=models.CharField(choices=[('PM', 'PM'), ('RT', 'Routine'), ('MT', 'Maintenance')], max_length=2),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
