# Generated by Django 5.2.4 on 2025-08-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_tasksubmission_cause_of_problem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='is_team_leader',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='task_type',
            field=models.CharField(choices=[('PM', 'Preventive Maintenance'), ('RT', 'Routine Task'), ('MT', 'Maintenance Task')], max_length=2),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='tasks_assigned', to='reports.engineer'),
        ),
    ]
